# Generated by Django 3.0.1 on 2019-12-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitystream', '0002_auto_20191218_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
